"""create pool tables

Revision ID: 7bf562a33435
Revises: b819ba6f5b5c
Create Date: 2026-04-16 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf562a33435'
down_revision: Union[str, None] = 'b819ba6f5b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_pool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_pool_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['stock_pool.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pool_item_unique', 'stock_pool_item', ['pool_id', 'ts_code'], unique=True)
    op.create_index(op.f('ix_stock_pool_item_pool_id'), 'stock_pool_item', ['pool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_pool_item_pool_id'), table_name='stock_pool_item')
    op.drop_index('ix_pool_item_unique', table_name='stock_pool_item')
    op.drop_table('stock_pool_item')
    op.drop_table('stock_pool')
    # ### end Alembic commands ###
