"""create quote tables

Revision ID: b819ba6f5b5c
Revises: 
Create Date: 2026-04-16 17:46:45.477635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b819ba6f5b5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_candle',
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('vol', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('adj_factor', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    op.create_index('ix_daily_candle_lookup', 'daily_candle', ['ts_code', 'trade_date'], unique=False)
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('searched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_ts_code'), 'search_history', ['ts_code'], unique=False)
    op.create_table('stock_basic',
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('area', sa.String(length=10), nullable=True),
    sa.Column('industry', sa.String(length=20), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_index(op.f('ix_stock_basic_name'), 'stock_basic', ['name'], unique=False)
    op.create_index(op.f('ix_stock_basic_symbol'), 'stock_basic', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_basic_symbol'), table_name='stock_basic')
    op.drop_index(op.f('ix_stock_basic_name'), table_name='stock_basic')
    op.drop_table('stock_basic')
    op.drop_index(op.f('ix_search_history_ts_code'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_table('favorite')
    op.drop_index('ix_daily_candle_lookup', table_name='daily_candle')
    op.drop_table('daily_candle')
    # ### end Alembic commands ###
